package network.amnesia.anbd.commands;

import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.interactions.commands.OptionType;
import net.dv8tion.jda.api.interactions.commands.build.SlashCommandData;
import network.amnesia.anbd.command.Command;
import network.amnesia.anbd.command.CommandCategory;
import network.amnesia.anbd.command.ICommand;

import java.util.Random;

@ICommand(name = "8ball", category = CommandCategory.FUN, description = "Ask the magic 8 ball a special question")
public class Magic8BallCommand extends Command {
    public Outcome invoke(SlashCommandInteractionEvent event, String question) {
        String[] answers = {
                "Absolutely !",
                "Yes, sure.",
                "For sure, dude !",
                "Maybe...",
                "Nah...",
                "No, really, no...",
                "As I see it, yes",
                "Better not tell you now",
                "Cannot predict now",
                "Don't count on it",
                "If you say so",
                "In your dreams",
                "It is certain",
                "Most likely",
                "My CPU is saying no",
                "My CPU is saying yes",
                "Out of psychic coverage range",
                "Signs point to yes",
                "Sure, sure",
                "Very doubtful",
                "When life gives you lemon, you drink it",
                "Without a doubt",
                "Wow, Much no, very yes, so maybe",
                "Yes, definitely",
                "Yes, unless you run out of memes",
                "You are doomed",
                "You can't handle the truth",
                "Without a doubt.",
                "It is certain.",
                "Yes, not a doubt in my mind.",
                "It is decidedly so.",
                "Yes, definitely.",
                "You may rely on it.",
                "As I see it, yes.",
                "Most likely.",
                "Outlook good.",
                "Signs point to yes.",
                "Ask again later.",
                "Reply hazy try again.",
                "Try again later.",
                "Better not tell you now.",
                "Cannot predict now.",
                "Concentrate and ask again.",
                "Don't count on it.",
                "My reply is no.",
                "My sources say no.",
                "Outlook not so good.",
                "Very doubtful.",
                "Yes.",
                "No.",
                "Yep.",
                "Nope.",
                "y35.",
                "n0.",
                "Only the prophecy will tell.",
                "Who cares? We all die in the end.",
                "Isn't it obvious?",
                "Obviously, yes.",
                "Yes, duh?",
                "I don't think so, no.",
                "Who gives a fuck?",
                "You wish.",
                "Is this a joke?",
                "Ask me if I care.",
                "Fuck do I know, I'm just a magic ball.",
                "No God, please, no.",
                "Just google it.",
                "Bitch, I don't know your life.",
                "Google might have the answer.",
                "Help! I'm trapped!",
                "Perhaps.",
                "Maybe, just maybe.",
                "You bet!",
                "Grow up and make your own decisions, idiot.",
                "Trust me, you don't want to know.",
                "No Ron.",
                "Ask Michael.",
                "Hell if I know.",
                "Barely possible.",
                "It's a secret to everybody.",
                "It depends.",
                "Don't take my word for it.",
                "Yeah, right.",
                "Sure, if you think so.",
                "In your dreams.",
                "Sounds good to me.",
                "Not yet.",
                "Probably.",
                "Very likely.",
                "Very unlikely.",
                "Not advisable.",
                "Give it time.",
                "When the planets align.",
                "You already know the answer to that.",
                "Maybe, in a few weeks, if you're lucky.",
                "Never in a million years, maybe in fewer.",
                "It smells like it.",
                "Possibly, but possibly it is impossible.",
                "They didn't allow me to tell you.",
                "No fucking way.",
                "Oh hell no!",
                "Kill them, kill all of them.",
                "Anything is possible.",
                "In theory, yes.",
                "I don't even know what to answer you.",
                "I don't know and I don't care.",
                "The answer is C.",
                "Ask me again tomorrow.",
                "I strongly believe so.",
                "It looks like it.",
                "I wouldn't worry about it.",
                "Go fish.",
                "NEXT QUESTION!",
                "yo that sounds lit fam",
                "Don't let your dreams be dreams.",
                "Follow your heart, I wouldn't trust your mind though.",
                "Sure, why not?",
                "Just ask yourself: \"Would John Cena do it?\"",
                "JUST DO IT!",
                "I might know the answer, but maybe a bribe can help me remember better...",
                "It depends, does it give you EXP?",
                "I rolled a dice to answer you, and it said the answer is C.",
                "\"Anything is possible.\" Said the blind boy as it proceeded to walk into a pit.",
                "42.",
                "It ain't worth it, m8.",
                "Would it make life better?",
                "Why are we still here?",
                "No! Think of the children!",
                "please save me she's forcing me to lie",
                "Short answer: Yes. Long answer: No.",
                "It all depends if you have a good kda ratio.",
                "I don't know, can a match box?",
                "If Leo won the Oscar and we got Finding Nemo 2, It's probably possible.",
                "What could possibly go wrong?",
                "What's the worse that could happen?",
                "Ah, I see you're an entity of culture as well.",
                "You should ask that bitch Alexa.",
                "You should ask that bitch Cortana.",
                "You should ask Siri, that slut.",
                "Mee6 is a hoe.",
                "Yes, not a doubt in my mind",
                "**SMALL PP ALERT**",
                "You are down astronomically bad.",
                "lol penis",
                "Why should I care?",
                "that was actually sad by my brother",
                "bitch lasagna",
                "No, you butterscotch bitch.",
                "You *really* are part of the bonehead brigade, aren't you?",
                "Riiiiight...moving on!",
                "tf???",
                "dont ask that ever again",
                "Your mother has a job and is a respected member of the community.",
                "if it involves big tiddy anime girls, then yes",
                "Absolutely (not)!",
                "stop the lies",
                "it iz what it iz",
                "hul yuh bumboclaat",
                "dawh hul yuh mudah rasclaat",
                "u need a life g",
                "Stop..... just stop",
                "No you fucking idiot",
                "I am the senate",
                "Sure, why not?",
                "Of course, dumbass",
                "I don't know but you sure are dummy thicc",
                "Stop talking to me and go get some bitches",
                "Sugma Nuts",
                "happy pride month :)",
                "get in my bed now.",
                "So, I hear you. But also, nice tits.",
                "Because COCKDICK",
                "Ante up and dont be a bitch",
                "What would scott the woz do",
                "Follow the prophecy of the spoons",
                "I make-a da meatballs",
                "Yes!!",
                "No!!!"
        };
        int randInt = new Random().nextInt(answers.length);

        event.reply("Question: " + question + "\n" + "Answer: " + answers[randInt]).queue();
        return Outcome.SUCCESS;
    }

    @Override
    public SlashCommandData getCommandData() {
        return super.getCommandData().addOption(OptionType.STRING, "question", "Ask the magic 8 ball a question with yes/no answer", true);
    }
}
