package network.amnesia.anbd.commands;

import com.fasterxml.jackson.core.JsonProcessingException;
import net.dv8tion.jda.api.entities.Message;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.interactions.commands.OptionType;
import net.dv8tion.jda.api.interactions.commands.build.SlashCommandData;
import network.amnesia.anbd.command.Command;
import network.amnesia.anbd.command.CommandCategory;
import network.amnesia.anbd.command.ICommand;
import network.amnesia.anbd.polls.CustomPoll;
import network.amnesia.anbd.polls.YesOrNoPoll;

import java.util.Objects;

@ICommand(name = "poll", category = CommandCategory.FUN, description = "Create a [Yes or No] poll or custom poll generated by https://anbd-pollbuilder.7dev.live/")
public class PollCommand extends Command {

    public Outcome invoke(SlashCommandInteractionEvent event, String question) throws JsonProcessingException {
        return invoke(event, question, false);
    }

    public Outcome invoke(SlashCommandInteractionEvent event, String question, Boolean change) throws JsonProcessingException {
        if (Objects.equals(question, "link")) { //get ANBD PollBuilder link
            event.reply("https://anbd-pollbuilder.7dev.live/").setEphemeral(true).queue();
            return Outcome.SUCCESS;
        }
        //PollBuilder JSON
        if (question.trim().charAt(0) == '{' && question.trim().charAt(question.length() - 1) == '}') {
            // verify question is a valid JSON data TODO
            CustomPoll poll = new CustomPoll(question, change);
            Message message = event.replyEmbeds(poll.getEmbed()).complete().retrieveOriginal().complete();
            poll.setPollMessageId(message.getIdLong());
            poll.addReactions(message);
            return Outcome.SUCCESS;
        }
        //Yes or No question
        YesOrNoPoll poll = new YesOrNoPoll(question, change);
        event.replyEmbeds(poll.getEmbed()).setActionRow(poll.yesButton, poll.noButton).queue();
        return Outcome.SUCCESS;
    }

    @Override
    public SlashCommandData getCommandData() {
        return super.getCommandData().addOption(OptionType.STRING, "question", "Your [Yes or No] question / Your PollBuilder JSON (Type \"link\" to get the link of PollBuilder)", true)
                .addOption(OptionType.BOOLEAN, "change", "Allow members to change their choice (false by default)", false);
    }
}